// -*-Mode: C++; tab-width: 4; c-basic-offset: 4;-*-
// vi:set ts=4 sw=4:
//
// SQLParserL.h --
// 
// Copyright (c) 1999, 2000, 2002, 2003, 2005, 2023 Ricoh Company, Ltd.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 

#define TOKEN__SEMICOLON                       1
#define TOKEN__UNION                           2
#define TOKEN__EXCEPT                          3
#define TOKEN__INTERSECT                       4
#define TOKEN__JOIN                            5
#define TOKEN__INNER                           6
#define TOKEN__LEFT                            7
#define TOKEN__RIGHT                           8
#define TOKEN__FULL                            9
#define TOKEN__NATURAL                        10
#define TOKEN__CROSS                          11
#define TOKEN__ON                             12
#define TOKEN__COMMA                          13
#define TOKEN__OR                             14
#define TOKEN__AND                            15
#define TOKEN__NOT                            16
#define TOKEN__BETWEEN                        17
#define TOKEN__IN                             18
#define TOKEN__EQUALS                         19
#define TOKEN__NOT_EQUALS                     20
#define TOKEN__LESS_THAN                      21
#define TOKEN__GREATER_THAN                   22
#define TOKEN__LESS_THAN_OR_EQUALS            23
#define TOKEN__GREATER_THAN_OR_EQUALS         24
#define TOKEN__IS                             25
#define TOKEN__LIKE                           26
#define TOKEN__CONTAINS                       27
#define TOKEN__ESCAPE                         28
#define TOKEN__LANGUAGE                       29
#define TOKEN__CALCULATOR                     30
#define TOKEN__SIMILAR                        31
#define TOKEN__COMBINER                       32
#define TOKEN__USING                          33
#define TOKEN__VERTICALLINE                   34
#define TOKEN__CONTAINS_MINUS                 35
#define TOKEN__AMPERSAND                      36
#define TOKEN__PLUS                           37
#define TOKEN__MINUS                          38
#define TOKEN__STRING_CONCAT                  39
#define TOKEN__ASTERISK                       40
#define TOKEN__SOLIDUS                        41
#define TOKEN__UNARY_MINUS                    42
#define TOKEN__STRING                         43
#define TOKEN__STRING_WITH_QUOTE              44
#define TOKEN__BINARY_STRING                  45
#define TOKEN__INTEGER_LITERAL                46
#define TOKEN__FLOAT_LITERAL                  47
#define TOKEN__DATE                           48
#define TOKEN__TIMESTAMP                      49
#define TOKEN__IDENTIFIER                     50
#define TOKEN__IDENTIFIER_WITH_QUOTE          51
#define TOKEN__NULL                           52
#define TOKEN__DEFAULT                        53
#define TOKEN__QUESTION_MARK                  54
#define TOKEN__USER                           55
#define TOKEN__CURRENT_USER                   56
#define TOKEN__SESSION_USER                   57
#define TOKEN__CURRENT_PATH                   58
#define TOKEN__PERIOD                         59
#define TOKEN__LEFT_BRACKET                   60
#define TOKEN__RIGHT_BRACKET                  61
#define TOKEN__ALL                            62
#define TOKEN__DISTINCT                       63
#define TOKEN__CORRESPONDING                  64
#define TOKEN__BY                             65
#define TOKEN__LEFT_PARENTHESIS               66
#define TOKEN__RIGHT_PARENTHESIS              67
#define TOKEN__SELECT                         68
#define TOKEN__INTO                           69
#define TOKEN__AS                             70
#define TOKEN__OUTPUT                         71
#define TOKEN__TO                             72
#define TOKEN__PATH                           73
#define TOKEN__WITH                           74
#define TOKEN__HINT                           75
#define TOKEN__FROM                           76
#define TOKEN__INPUT                          77
#define TOKEN__FOR                            78
#define TOKEN__OUTER                          79
#define TOKEN__EXISTS                         80
#define TOKEN__UNNEST                         81
#define TOKEN__WHERE                          82
#define TOKEN__GROUP                          83
#define TOKEN__HAVING                         84
#define TOKEN__ORDER                          85
#define TOKEN__ASC                            86
#define TOKEN__DESC                           87
#define TOKEN__PARTITION                      88
#define TOKEN__OFFSET                         89
#define TOKEN__LIMIT                          90
#define TOKEN__SCALE                          91
#define TOKEN__PARAMETER                      92
#define TOKEN__WORD                           93
#define TOKEN__WORDLIST                       94
#define TOKEN__FREETEXT                       95
#define TOKEN__CATEGORY                       96
#define TOKEN__WEIGHT                         97
#define TOKEN__SYNONYM                        98
#define TOKEN__EXPAND_SYNONYM                 99
#define TOKEN__HEAD                           100
#define TOKEN__TAIL                           101
#define TOKEN__WITHIN                         102
#define TOKEN__SYMMETRIC                      103
#define TOKEN__ASYMMETRIC                     104
#define TOKEN__EXACTWORD                      105
#define TOKEN__SIMPLEWORD                     106
#define TOKEN__CONTAINS_STRING                107
#define TOKEN__WORDHEAD                       108
#define TOKEN__WORDTAIL                       109
#define TOKEN__UPPER                          110
#define TOKEN__LOWER                          111
#define TOKEN__AVERAGE                        112
#define TOKEN__LENGTH                         113
#define TOKEN__FULLTEXT                       114
#define TOKEN__DF                             115
#define TOKEN__SCORE                          116
#define TOKEN__FUNCTION                       117
#define TOKEN__EXPAND                         118
#define TOKEN__RANK                           119
#define TOKEN__EXTRACTOR                      120
#define TOKEN__CLUSTERED                      121
#define TOKEN__SUBSTRING                      122
#define TOKEN__OF                             123
#define TOKEN__OVERLAY                        124
#define TOKEN__PLACING                        125
#define TOKEN__NORMALIZE                      126
#define TOKEN__KWIC                           127
#define TOKEN__ENCLOSE                        128
#define TOKEN__ELLIPSIS                       129
#define TOKEN__ABS                            130
#define TOKEN__MOD                            131
#define TOKEN__GET                            132
#define TOKEN__MAX                            133
#define TOKEN__COUNT                          134
#define TOKEN__AVG                            135
#define TOKEN__SUM                            136
#define TOKEN__CURRENT_DATE                   137
#define TOKEN__CURRENT_TIMESTAMP              138
#define TOKEN__CASE                           139
#define TOKEN__END                            140
#define TOKEN__WHEN                           141
#define TOKEN__THEN                           142
#define TOKEN__ELSE                           143
#define TOKEN__MIN                            144
#define TOKEN__SECTIONIZED                    145
#define TOKEN__ARRAY                          146
#define TOKEN__ROW                            147
#define TOKEN__VALUES                         148
#define TOKEN__TABLE                          149
#define TOKEN__DELETE                         150
#define TOKEN__INSERT                         151
#define TOKEN__UPDATE                         152
#define TOKEN__SET                            153
#define TOKEN__START                          154
#define TOKEN__TRANSACTION                    155
#define TOKEN__READ                           156
#define TOKEN__ONLY                           157
#define TOKEN__WRITE                          158
#define TOKEN__ISOLATION                      159
#define TOKEN__LEVEL                          160
#define TOKEN__UNCOMMITTED                    161
#define TOKEN__COMMITTED                      162
#define TOKEN__REPEATABLE                     163
#define TOKEN__SERIALIZABLE                   164
#define TOKEN__SNAPSHOT                       165
#define TOKEN__COMMIT                         166
#define TOKEN__WORK                           167
#define TOKEN__ROLLBACK                       168
#define TOKEN__XA                             169
#define TOKEN__RESUME                         170
#define TOKEN__SUSPEND                        171
#define TOKEN__MIGRATE                        172
#define TOKEN__PREPARE                        173
#define TOKEN__ONE                            174
#define TOKEN__PHASE                          175
#define TOKEN__RECOVER                        176
#define TOKEN__FORGET                         177
#define TOKEN__CREATE                         178
#define TOKEN__DATABASE                       179
#define TOKEN__LOGICALLOG                     180
#define TOKEN__SYSTEM                         181
#define TOKEN__ONLINE                         182
#define TOKEN__OFFLINE                        183
#define TOKEN__DISCARD                        184
#define TOKEN__RECOVERY                       185
#define TOKEN__CHECKPOINT                     186
#define TOKEN__DROP                           187
#define TOKEN__ALTER                          188
#define TOKEN__SLAVE                          189
#define TOKEN__STOP                           190
#define TOKEN__MASTER                         191
#define TOKEN__GLOBAL                         192
#define TOKEN__TEMPORARY                      193
#define TOKEN__LOCAL                          194
#define TOKEN__CONSTANT                       195
#define TOKEN__UPDATABLE                      196
#define TOKEN__NVARCHAR                       197
#define TOKEN__VARCHAR                        198
#define TOKEN__NTEXT                          199
#define TOKEN__INT                            200
#define TOKEN__BIGINT                         201
#define TOKEN__FLOAT                          202
#define TOKEN__DATETIME                       203
#define TOKEN__UNIQUEIDENTIFIER               204
#define TOKEN__IMAGE                          205
#define TOKEN__NCHAR                          206
#define TOKEN__CHAR                           207
#define TOKEN__BINARY                         208
#define TOKEN__BLOB                           209
#define TOKEN__NCLOB                          210
#define TOKEN__DEC                            211
#define TOKEN__DECIMAL                        212
#define TOKEN__NUMERIC                        213
#define TOKEN__NO                             214
#define TOKEN__PRIMARY                        215
#define TOKEN__KEY                            216
#define TOKEN__UNIQUE                         217
#define TOKEN__CONST                          218
#define TOKEN__GENERATED                      219
#define TOKEN__IDENTITY                       220
#define TOKEN__ALWAYS                         221
#define TOKEN__INCREMENT                      222
#define TOKEN__MAXVALUE                       223
#define TOKEN__MINVALUE                       224
#define TOKEN__CYCLE                          225
#define TOKEN__FOREIGN                        226
#define TOKEN__REFERENCES                     227
#define TOKEN__COLUMN                         228
#define TOKEN__FILE                           229
#define TOKEN__INDEX                          230
#define TOKEN__TRIGGER                        231
#define TOKEN__HEAP                           232
#define TOKEN__NONTRUNCATE                    233
#define TOKEN__IF                             234
#define TOKEN__AREA                           235
#define TOKEN__PHYSICALLOG                    236
#define TOKEN__RENAME                         237
#define TOKEN__ADD                            238
#define TOKEN__NONCLUSTERED                   239
#define TOKEN__BITMAP                         240
#define TOKEN__ROWS                           241
#define TOKEN__KDTREE                         242
#define TOKEN__MODIFY                         243
#define TOKEN__UNMOUNT                        244
#define TOKEN__MOUNT                          245
#define TOKEN__BACKUP                         246
#define TOKEN__VERIFY                         247
#define TOKEN__CORRECT                        248
#define TOKEN__CONTINUE                       249
#define TOKEN__CASCADE                        250
#define TOKEN__VERBOSE                        251
#define TOKEN__VALUE                          252
#define TOKEN__SYNC                           253
#define TOKEN__DISCONNECT                     254
#define TOKEN__SESSION                        255
#define TOKEN__CONNECTION                     256
#define TOKEN__DECLARE                        257
#define TOKEN__GRANT                          258
#define TOKEN__REVOKE                         259
#define TOKEN__EXPLAIN                        260
#define TOKEN__EXECUTE                        261
#define TOKEN__RETURNS                        262
#define TOKEN__RETURN                         263

//
// Copyright (c) 1999, 2000, 2002, 2003, 2005, 2023 Ricoh Company, Ltd.
// All rights reserved.
//
