#
# c/Makefile ---
# 
# Copyright (c) 1999, 2023 Ricoh Company, Ltd.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

SOURCES =						\
	../../../../Kernel/DPlan/Relation/*.cpp		\
	../../../../Kernel/DPlan/Relation/Impl/*.cpp
LOCALINCL = -I../../../../Kernel/DPlan \
	-I../../../../Kernel/Plan

all:
	$(MAKE) "SOURCES=$(SOURCES)" "LOCALINCL=$(LOCALINCL)" -f $(MAKEFILE_H_MAK)

#
# Copyright (c) 1999, 2023 Ricoh Company, Ltd.
# All rights reserved.
#
